services:
  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: genealogy
      MYSQL_USER: stage_svp
      MYSQL_PASSWORD: stage_svp
    ports:
      - "8001:3306"
  
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: genealogy
      DB_USERNAME: stage_svp
      DB_PASSWORD: stage_svp
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    command: php artisan serve --host=0.0.0.0 --port=8000
    
volumes:
  db_data: